lint:
  rules:
    no_default: false
    remove:
      - ENUM_FIELD_NAMES_PREFIX
      - MAX_LINE_LENGTH
    indent:
      # Available styles are 4(4-spaces), 2(2-spaces) or tab.
      style:
        - 2
        - 4
        - tab
